[package]
name = "autobuild-ng"
version = "0.2.5"
description = "A test project aimed to create automatic releases by leveraging CI/CD in GitHub"
authors = ["Kiwifuit <75169058+Kiwifuit@users.noreply.github.com>"]
license = "MIT"
edition = "2024"

[package.metadata.deb]
extended-description = """
`autobuild-ng` is a simple Ratatui application that demonstrates the
use of GitHub Actions to create automatic releases. When installed,
it shows Ratatui's simple TUI app template.
"""

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
color-eyre = "0.6.3"
