name: Build & Release code

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - target: x86_64-unknown-linux-gnu
            bin: autobuild.x86

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-deb
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deb

      - name: Build binary
        run: cargo build --release --target ${{ matrix.platform.target }}

      - name: Build deb package
        run: cargo deb --target ${{ matrix.platform.target }}
        if: contains(${{ matrix.platform.target }}, 'linux')

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bin.autobuild-ng.${{ matrix.platform.target }}
          path: target/release/autobuild-ng

      - name: Upload deb artifact
        uses: actions/upload-artifact@v4
        if: contains(${{ matrix.platform.target }}, 'linux')
        with:
          name: deb.autobuild-ng.${{ matrix.platform.target }}
          path: target/debian/autobuild-ng_*.deb

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        id: artifacts

      - name: Show artifacts
        run: |
          ls -laR ${{ steps.artifacts.download-path }}